name = "solar-theme-hugo"
license = "GPLv2"
licenselink = "https://github.com/bake/solar-theme-hugo/blob/master/LICENSE.md"
description = "A light or dark minimalistic theme"
homepage = "https://github.com/bake/solar-theme-hugo"
tags = ["blog", "light", "dark", "responsive", "solarized", "highlight.js"]
features = []
min_version = "0.25.1"

[author]
	name = "bake"
	homepage = "https://192k.pw/"

[original]
	author = "mattvh"
	name = "solar-theme-ghost"
	repo = "https://github.com/mattvh/solar-theme-ghost"
